### ISSUE TITLE
Wireframes erstellen

### ISSUE THREAD

**Issue by Snapstromegon** [Snapstromegon/TH-SS19-WD-Projekt#1]
Wireframes erstellen für:

- [x] Mobil
  - [x] Gallerie
  - [x] Detail
  - [x] Fullscreen Bild
- [x] Tablet
  - [x] Gallerie
  - [x] Detail
  - [x] Fullscreen Bild
- [x] Desktop
  - [x] Gallerie
  - [x] Detail
  - [x] Fullscreen Bild

### Gallerie

Übersicht über alle Bilder mit Titeln mit paginierung

### Detail

Kleines Vorschaubild mit Metainformationen der Bilder mit Paginierung

### Fullscreen

Zoombare Vollbildansicht der Bilder

**Comment by Snapstromegon** [comment]
![TH-SS19-WD-Projekt](https://user-images.githubusercontent.com/18480654/62071900-c5a22d80-b23d-11e9-8a6b-6be0eb550010.jpg)

**Comment by Snapstromegon** [comment]
@Madoka03 Bitte einmal ein Review dazu und wenn ok closen

**Comment by Madoka03** [comment]
Kann so bleiben und weiter ausgearbeitet werden für die Umsetzung in Code. 👍
