### ISSUE TITLE
Pagination: Verhalten auf erster und letzter Seite

### ISSUE THREAD

**Issue by Madoka03** [Snapstromegon/TH-SS19-WD-Projekt#10]
Zur Auwahl standen 2 Optionen:

- vor bzw. zurück nicht klickbar und optisch verändert
- von erster zurück auf die letzte Seite

Im Feedback-Termin war das Ergebnis eher eine Tendenz zu Option 1. Habe das auch bereits in einem Commit adressiert und so umgesetzt. 

Für Feedback hier kommentieren und closen wenn so alles ok ist. @Snapstromegon  Wenn dir das Grau nicht gefällt kannst du es auch einfach selbst schnell anpassen.

**Comment by Snapstromegon** [comment]
es gibt eine optische Änderung, die ist aber meiner Meinung nach viel zu klein (ich habe zuerst, obwohl ich die Änderung wusste, gedacht es wäre eine Bug und hätte nicht funktioniert). Ich schlage vor statt von #fff zu #ccc von #fff zu #888 zu ändern. So sieht man die Änderung deutlich.

**Comment by Madoka03** [comment]
Da du gemerged hast sollte jetzt alles passen, daher close.
