### ISSUE TITLE
Bildtitel in der Gallery View kürzen

### ISSUE THREAD

**Issue by Madoka03** [Snapstromegon/TH-SS19-WD-Projekt#11]
Zu lange Bildtitel werde gekürzt und drei Punkte angefügt.
Commit be62d82bd9e0dd4fa9fe3afc674f514c45811815

Feedback @Snapstromegon

**Comment by Snapstromegon** [comment]
Ist zwar manchmal nicht perfekt, aber das CSS Ding kann keine mehrzeilgen Sachen, daher ist die aktuelle Lösung okay.
