### ISSUE TITLE
Umsetzung mit Vue.js und SFCs

### ISSUE THREAD

**Issue by Madoka03** [Snapstromegon/TH-SS19-WD-Projekt#7]
Implementierung der App mit Vue.js und SFCs und dem Template aus #4. 
Branch: dev

- [x] Gallery View
- [x] Detail View
- [x] Fullsize View

**Comment by Madoka03** [comment]
@Snapstromegon Funktional sollte erstmal alles Implementiert sein, Verbesserungsvorschläge und falls ich was vergessen habe bitte hier rein posten.
Ein Live Server mit Hotreloading lässt sich leicht starten, siehe einfach in der package.json.

**Comment by Snapstromegon** [comment]
Die Bannertexte der Bilder funktionieren nicht als Link.

**Comment by Snapstromegon** [comment]
Single tap für fullscreen reicht meiner Meinung nach - sieht sonst sehr gut aus

**Comment by Snapstromegon** [comment]
der zurück button in der top bar sollte nicht zurücknavigieren, sondern zur übergeordneten Ansicht

Erwartet:
Galerie -> Details -> nach links oder rechts navigieren -> zurück
Jetzt sollte man wieder in der Galerie sein, man ist aber in der Detailansicht des ersten Bildes

**Comment by Snapstromegon** [comment]
Bilder mit srcset verwenden und versuchen das original zu laden, wenn verfügbar, sonst fallback preview verwenden

**Comment by Madoka03** [comment]
> Die Bannertexte der Bilder funktionieren nicht als Link.

Sollte mit dem Commit `image title as clickable link #7` behoben sein.
